### ISSUE TITLE
Export the Complexity results in excel

### ISSUE THREAD

**Issue by thangaraja** [kisstkondoros/codemetrics#108]
Hi,

This extension is really great. But is there a way to export the results (i.e the complete complexity of the project) to the excel file?

It would be super helpful for code review.

**Comment by c0ncentus** [comment]
owners dont want do that because too complex (lol), you can do that on a particular extention of webpack.

=> webpack is a great tool but if you're use it you fellow a tuto or do as "expert".
=> not every repo want to include webpack because of the sake of KPI, typescript has already "tsc" for compiling.
=> The tool should have name "complexity lint" rather than "CodeMetrics".

it's remind me how much hell exist in sonarqube's world to install and use xD.

No tool that I know use score (number) as output for complexity and enhance knowledge for devs.

**Comment by kisstkondoros** [comment]
There is an example cli tool at https://github.com/kisstkondoros/codemetrics-cli
It is not a goal of this extension to report to any file at all.

**Comment by Xeyos88** [comment]
> There is an example cli tool at https://github.com/kisstkondoros/codemetrics-cli It is not a goal of this extension to report to any file at all.

Hi,
I am quoting this answer because I am also interested in this topic.
I saw that the extension works well for Vue projects, but the cli instead only ansalizes js or ts files. Will it be updated?
