### ISSUE TITLE
Typescript - Complexity information shown on classes but not on functions

### ISSUE THREAD

**Issue by pbalaga** [kisstkondoros/codemetrics#13]
Hi, I've just installed the extension (v 1.2.0) in VS Code. It shows complexity at the top of a class declaration, but not for individual methods. Having seen the example screenshots, it may not be working as designed. I would expect complexity to be shown on top of functions. Additionally, it seems class complexity is calculated as sum of member complexities, which is arguably OK, but is there would need to be different complexity limits for classes and class memebers. (5 max limit is good for functions, but not so much for classes - code in the below example already breaks the limit.)

![image](https://cloud.githubusercontent.com/assets/14298228/23831057/729f126e-0719-11e7-8050-388e9e9e1f28.png)

**Comment by kisstkondoros** [comment]
Hi,

What you experience here is the effect of the configuration option: "codemetrics.basics.CodeLensHiddenUnder" the default of this is 3, this means that every codelens with complexity 3 and below is going to be hidden, you can change this to be 0 so that you see every single one of them.

> it seems class complexity is calculated as sum of member complexities

Right, I haven't implemented a special case for classes. If you have an idea how it can be done in a better way, feel free to open a PR or just describe what you would expect there.

**Comment by pbalaga** [comment]
Thanks, this makes sense.
