### ISSUE TITLE
`return` make code complexity??

### ISSUE THREAD

**Issue by tangweikun** [kisstkondoros/codemetrics#47]
Every time add one `return`, the complexity will increase 1, it's a cool rule?
That's my first time know about `return` make code complexity, can you help me understand about this!

**Comment by kisstkondoros** [comment]
You might have heard about the principle of [single-entry single-exit](https://en.wikipedia.org/wiki/Single-entry_single-exit).
Or to make it more clear have a look at the page about [control flow graph](https://en.wikipedia.org/wiki/Control_flow_graph)

So the point is, that adding a return statement can make the code harder to grasp.

consider the following as an example:
```typescript
tagNameToType(tagname: string): string {
    switch (tagname) {
        case "div": return "element";
        case "paper-input":
        case "input": return "input";
        default:
            return undefined;
    }
}
```
vs.
```typescript
tagNameToType(tagname: string): string {
    let type: string;
    switch (tagname) {
        case "div": type = "element";
        case "paper-input":
        case "input": type = "input";
        default:
            type = undefined;
    }
    return type;
}
```

For me at least it is easier to understand what the latter does.
Since it might be a matter of personal taste however, it can be configured (also many other things) in the workspace / user settings:
```json
"codemetrics.nodeconfiguration.ReturnStatement": 0
```

**Comment by tangweikun** [comment]
Thanks very much, this plugin is pretty awesome
That `return` staff is about my personal style, so I will keep use return as before
