### ISSUE TITLE
Single place to see overall complexity of the file and project

### ISSUE THREAD

**Issue by vimalraj-a** [kisstkondoros/codemetrics#56]
I would like to see the overall complexity of the module and file in report. That would make my life easier than going into the file and seeing the complexity.

Is there any way to get report out of this plugin and can be used in CI Integration ?

**Comment by kisstkondoros** [comment]
This is out of scope for this particular extension.

BUT!

The functionality was requested already in #32 and I've came up with
- a simple webpack plugin
-- repo: https://github.com/kisstkondoros/tsmetrics-webpack-plugin
-- npm: https://www.npmjs.com/package/tsmetrics-webpack-plugin

- and an example for gulp
-- https://github.com/kisstkondoros/gulp-tsmetrics

Based on these, one can come up with a CLI tool easily, but I have no plans for supporting it.

Please note that the repos and the npm package is outdated, since I have no interest in keeping them up to date. (actual usage vary anyway amongst projects).

I hope this answered Your question!

I'm closing the issue for now.
