### ISSUE TITLE
Cognitive Complexity

### ISSUE THREAD

**Issue by lnfnunes** [kisstkondoros/codemetrics#57]
Is there a roadmap or planning to implement Cognitive Complexity?

**References:**
- https://blog.sonarsource.com/cognitive-complexity-because-testability-understandability
- https://docs.codeclimate.com/docs/cognitive-complexity

**Comment by kisstkondoros** [comment]
Short answer: no, I have no plans for that.

Reason: mainly because the existing complexity metrics is already a pain for most of the users of the extension. You can get pretty close to the idea described in the paper by tuning the flags under codemetrics.nodeconfiguration... see [package.json](https://github.com/kisstkondoros/codemetrics/blob/master/package.json) for the full list of configuration parameters.

The only difference which can not be configured at the moment is the aggregation of the increments considering the special handling of the nesting increment. 
This could be implemented in the tsmetrics-core repo (+ some sorcery in codemetrics/.../server/LuaMetrics.ts).

PR's are always welcomed however! :smile:
