### ISSUE TITLE
'Arrow setting' does not work

### ISSUE THREAD

**Issue by Hypenate** [kisstkondoros/codemetrics#62]
In the settings, I have disabled the code metrics for the arrow functions.
![image](https://user-images.githubusercontent.com/7478681/47701653-d5db9c80-dc1a-11e8-9772-2e4f95f22b6d.png)
But when I check in my CodeLens it still counts.
![image](https://user-images.githubusercontent.com/7478681/47701623-b5134700-dc1a-11e8-8171-87fd4f2671f5.png)

**Comment by kisstkondoros** [comment]
If you would like to remove the complexity associated with an arrow function, then set the value of the Arrow Function to 0 (the field in the middle the scrrenshot above). The boolean option is meant for showing / hiding complexity code lenses at arrow functions.

**Comment by seiftie** [comment]
Still not fixed though. I have the same issue, setting the value to 0 doesn't fix the issue.

**Comment by kisstkondoros** [comment]
@seiftie I've just tested this and it does work...
There was also nothing to be fixed in the first place, perhaps I'm missing something?

In order to hide code lens for arrow functions turn the flag off
```"codemetrics.basics.MetricsForArrowFunctionsToggled": false```
To reduce the added complexity of arrow functions to zero, set the following too
```"codemetrics.nodeconfiguration.ArrowFunction": 0```

or in the UI:
![image](https://user-images.githubusercontent.com/14231157/74766978-4c743180-5286-11ea-9183-bf25f350a8b5.png)
